-- Integrantes:
-- Augusto Barcelos Barros ; RM: 98078
-- Gabriel Gribl de Carvalho ; RM: 96270
-- Gabriel Souza de Queiroz ; RM: 98570
-- Gabriela Zanotto Alves Rodrigues ; RM: 551629


-- Apaga todas as tabelas que podem existir no ambiente
DROP TABLE APLICATIVO CASCADE CONSTRAINTS;

DROP TABLE CHAMADO CASCADE CONSTRAINTS;

DROP TABLE SEGURADO CASCADE CONSTRAINTS;

DROP TABLE VEICULO CASCADE CONSTRAINTS;

DROP TABLE MOTORISTA CASCADE CONSTRAINTS;

DROP TABLE CHAMADO_PORTO CASCADE CONSTRAINTS;

DROP TABLE GUINCHO CASCADE CONSTRAINTS;

DROP TABLE GUINCHO_MOTORISTA CASCADE CONSTRAINTS;

DROP TABLE LOCALIZADOR CASCADE CONSTRAINTS;

DROP TABLE PORTO CASCADE CONSTRAINTS;

-- Cria tabela aplicativo
CREATE TABLE APLICATIVO (
    VERSAO CHAR(10 CHAR) NOT NULL,
    NOME VARCHAR2(20 CHAR),
    PLATAFORMA CHAR(10 CHAR),
    TAMANHO INTEGER,
    DESCRICAO VARCHAR2(50 CHAR)
);

ALTER TABLE APLICATIVO ADD CONSTRAINT APLICATIVO_PK PRIMARY KEY ( VERSAO );

-- Cria tabela chamado
CREATE TABLE CHAMADO (
    NUM_CHAMADO INTEGER NOT NULL,
    PRIORIDADE VARCHAR2(15 CHAR),
    STATUS CHAR(20 CHAR),
    DATA DATE,
    CATEGORIA CHAR(10 CHAR),
    APLICATIVO_VERSAO CHAR(10 CHAR) NOT NULL
);

ALTER TABLE CHAMADO ADD CONSTRAINT CHAMADO_PK PRIMARY KEY ( NUM_CHAMADO );

-- Cria tabela chamado_porto
CREATE TABLE CHAMADO_PORTO (
    NUM_PROTOCOLO INTEGER NOT NULL,
    DESCRICAO VARCHAR2(50 CHAR),
    MODELO_VEICULO VARCHAR2(30 CHAR),
    CHASSI CHAR(30 CHAR),
    CHAMADO_NUM_CHAMADO INTEGER NOT NULL,
    PORTO_CNPJ VARCHAR2(18 CHAR) NOT NULL
);

ALTER TABLE CHAMADO_PORTO ADD CONSTRAINT CHAMADO_PORTO_PK PRIMARY KEY ( NUM_PROTOCOLO );

-- Cria tabela guincho
CREATE TABLE GUINCHO (
    ID_GUINCHO INTEGER NOT NULL,
    PLACA VARCHAR2(8 CHAR),
    MODELO VARCHAR2(100 CHAR),
    ANO_FABRICACAO CHAR(4 CHAR),
    ALTURA INTEGER,
    PESO INTEGER,
    COMPRIMENTO INTEGER,
    LARGURA INTEGER,
    LOCALIZADOR_ID_GUINCHO INTEGER NOT NULL
);

ALTER TABLE GUINCHO ADD CONSTRAINT GUINCHO_PK PRIMARY KEY ( ID_GUINCHO );

-- Cria tabela guincho_motorista
CREATE TABLE GUINCHO_MOTORISTA (
    CNH VARCHAR2(11 CHAR) NOT NULL,
    NOME VARCHAR2(50 CHAR),
    MOTORISTA_ID_MOTORISTA INTEGER NOT NULL,
    GUINCHO_ID_GUINCHO INTEGER NOT NULL
);

ALTER TABLE GUINCHO_MOTORISTA ADD CONSTRAINT GUINCHO_MOTORISTA_PK PRIMARY KEY ( CNH );

-- Cria tabela localizador
CREATE TABLE LOCALIZADOR (
    ID_GUINCHO INTEGER NOT NULL,
    STATUS VARCHAR2(15 CHAR),
    ENDERECO VARCHAR2(50 CHAR)
);

ALTER TABLE LOCALIZADOR ADD CONSTRAINT LOCALIZADOR_PK PRIMARY KEY ( ID_GUINCHO );

-- Cria tabela motorista
CREATE TABLE MOTORISTA (
    ID_MOTORISTA INTEGER NOT NULL,
    NOME VARCHAR2(50 CHAR),
    SALARIO INTEGER,
    TELEFONE VARCHAR2(20 CHAR),
    EMAIL VARCHAR2(50 CHAR)
);

ALTER TABLE MOTORISTA ADD CONSTRAINT MOTORISTA_PK PRIMARY KEY ( ID_MOTORISTA );

-- Cria tabela porto
CREATE TABLE PORTO (
    CNPJ VARCHAR2(18 CHAR) NOT NULL,
    TELEFONE VARCHAR2(20 CHAR),
    EMAIL VARCHAR2(50 CHAR),
    GUINCHO_ID_GUINCHO INTEGER NOT NULL
);

ALTER TABLE PORTO ADD CONSTRAINT PORTO_PK PRIMARY KEY ( CNPJ );

-- Cria tabela segurado
CREATE TABLE SEGURADO (
    ID_SEGURADO INTEGER NOT NULL,
    NOME VARCHAR2(50 CHAR),
    TELEFONE VARCHAR2(20 CHAR),
    EMAIL VARCHAR2(50 CHAR),
    CPF VARCHAR2(11 CHAR),
    APLICATIVO_VERSAO CHAR(10 CHAR) NOT NULL,
    MOTORISTA_ID_MOTORISTA INTEGER NOT NULL
);

ALTER TABLE SEGURADO ADD CONSTRAINT SEGURADO_PK PRIMARY KEY ( ID_SEGURADO );

-- Cria tabela veiculo
CREATE TABLE VEICULO (
    ID_VEICULO INTEGER NOT NULL,
    PLACA VARCHAR2(8 CHAR),
    MODELO VARCHAR2(30 CHAR),
    ANO_FABRICACAO CHAR(4 CHAR),
    ALTURA INTEGER,
    PESO INTEGER,
    LARGURA INTEGER,
    COMPRIMENTO INTEGER,
    SEGURADO_ID_SEGURADO INTEGER NOT NULL,
    GUINCHO_ID_GUINCHO INTEGER NOT NULL
);

ALTER TABLE VEICULO ADD CONSTRAINT VEICULO_PK PRIMARY KEY ( ID_VEICULO );

-- Cria as FK necessárias
ALTER TABLE CHAMADO ADD CONSTRAINT CHAMADO_APLICATIVO_FK FOREIGN KEY ( APLICATIVO_VERSAO ) REFERENCES APLICATIVO ( VERSAO );

ALTER TABLE CHAMADO_PORTO ADD CONSTRAINT CHAMADO_PORTO_CHAMADO_FK FOREIGN KEY ( CHAMADO_NUM_CHAMADO ) REFERENCES CHAMADO ( NUM_CHAMADO );

ALTER TABLE CHAMADO_PORTO ADD CONSTRAINT CHAMADO_PORTO_PORTO_FK FOREIGN KEY ( PORTO_CNPJ ) REFERENCES PORTO ( CNPJ );

ALTER TABLE GUINCHO ADD CONSTRAINT GUINCHO_LOCALIZADOR_FK FOREIGN KEY ( LOCALIZADOR_ID_GUINCHO ) REFERENCES LOCALIZADOR ( ID_GUINCHO );

ALTER TABLE GUINCHO_MOTORISTA ADD CONSTRAINT GUINCHO_MOTORISTA_GUINCHO_FK FOREIGN KEY ( GUINCHO_ID_GUINCHO ) REFERENCES GUINCHO ( ID_GUINCHO );

ALTER TABLE GUINCHO_MOTORISTA ADD CONSTRAINT GUINCHO_MOTORISTA_MOTORISTA_FK FOREIGN KEY ( MOTORISTA_ID_MOTORISTA ) REFERENCES MOTORISTA ( ID_MOTORISTA );

ALTER TABLE PORTO ADD CONSTRAINT PORTO_GUINCHO_FK FOREIGN KEY ( GUINCHO_ID_GUINCHO ) REFERENCES GUINCHO ( ID_GUINCHO );

ALTER TABLE SEGURADO ADD CONSTRAINT SEGURADO_APLICATIVO_FK FOREIGN KEY ( APLICATIVO_VERSAO ) REFERENCES APLICATIVO ( VERSAO );

ALTER TABLE SEGURADO ADD CONSTRAINT SEGURADO_MOTORISTA_FK FOREIGN KEY ( MOTORISTA_ID_MOTORISTA ) REFERENCES MOTORISTA ( ID_MOTORISTA );

ALTER TABLE VEICULO ADD CONSTRAINT VEICULO_GUINCHO_FK FOREIGN KEY ( GUINCHO_ID_GUINCHO ) REFERENCES GUINCHO ( ID_GUINCHO );

ALTER TABLE VEICULO ADD CONSTRAINT VEICULO_SEGURADO_FK FOREIGN KEY ( SEGURADO_ID_SEGURADO ) REFERENCES SEGURADO ( ID_SEGURADO );

-- Inserção de 7  linhas  de dados (INSERT); [20 pontos]?
INSERT INTO MOTORISTA VALUES (1, 'Antonio', 1400, '1931677642', 'antonio@gmail.com' );
INSERT INTO MOTORISTA VALUES (2, 'Joao', 2300, '1939763337', 'joao@gmail.com' );
INSERT INTO MOTORISTA VALUES (3, 'Maria', 2000, '1934362625', 'maria@gmail.com' );

INSERT INTO APLICATIVO VALUES ('1.0', 'Guincho', 'Android', 10, 'Aplicativo para solicitar guincho');

INSERT INTO SEGURADO VALUES (1, 'Gabriel Gribl de Carvalho', '11950622003', 'gabrielgribl.118@gmail.com', '52190969824', '1.0', 1);
INSERT INTO SEGURADO VALUES (2, 'Cleide Dias Gribl', '11987204836', 'cleide_gribl@hotmail.com,', '07100842859', '1.0', 2);
INSERT INTO SEGURADO VALUES (3, 'Vania Aparecida Dias Gribl', '11989461946', 'vania_aparecida@hotmail.com,', '08019404864', '1.0', 3);
INSERT INTO SEGURADO VALUES (4, 'Gustavo Gribl de Carvalho', '11995677455', 'gustavogribl@hotmail.com,', '52190995825', '1.0', 1);
INSERT INTO SEGURADO VALUES (5, 'Marcos Pitarello', '11950762275', 'marcoos.pitarello@gmail.com', '53487042886', '1.0', 2);
INSERT INTO SEGURADO VALUES (6, 'Gabriel Moura de Souza', '11953682131', 'gabrielmourasouza@hotmail.com', '47258664823', '1.0', 3);
INSERT INTO SEGURADO VALUES (7, 'Julia Romeiro', '11977345171', 'Juliajrp123@gmail.com', '49804905817', '1.0', 1);

INSERT INTO LOCALIZADOR VALUES (1, 'Disponivel', 'Rua Genofre, 97');

INSERT INTO GUINCHO VALUES (1, 'ABC1234', 'GUINCHO PLATAFORMA AUTO SOCORRO RAPTOR', '1970', 2.5, 6000, 5, 2, 1);

INSERT INTO VEICULO VALUES (1, 'XYZ123', 'Fusca', '2022', 1.5, 1000, 3.8, 1.6, 2, 1);
INSERT INTO VEICULO VALUES (2, 'GBH3892', 'Tesla X', '2021', 1.5, 1400, 2.4, 2, 4, 1);


-- 3 exemplos de Atualização de dados (UPDATE); [10 pontos]?
UPDATE SEGURADO SET NOME = 'Gabriel Gribl de Andrade' WHERE ID_SEGURADO = 1;
UPDATE SEGURADO SET NOME = 'Cleide Dias Souza' WHERE ID_SEGURADO = 2;
UPDATE SEGURADO SET NOME = 'Vania Aparecida Dias Carvalho' WHERE ID_SEGURADO = 3;

UPDATE MOTORISTA SET NOME = 'Antonieta' WHERE ID_MOTORISTA = 1;

-- 3 exemplos de Remoção de dados (DELETE); [10 pontos]?
DELETE FROM SEGURADO WHERE ID_SEGURADO = 3;
DELETE FROM SEGURADO WHERE ID_SEGURADO = 6;

DELETE FROM MOTORISTA WHERE ID_MOTORISTA = 3;


-- Relatório utilizando classificação de dados, a escolha da tabela é decisão do grupo; [5 pontos]?
-- Retorna todos os segurados ordenados por nome de forma decrescente
SELECT * FROM SEGURADO ORDER BY NOME DESC;

-- Relatório utilizando alguma função do tipo numérica simples; [5 pontos]?
-- Retorna a média salarial dos motoristas
SELECT AVG(SALARIO) AS MEDIA_SALARIO FROM MOTORISTA;

-- Relatório utilizando alguma função de grupo; [10 pontos]?
-- Retorna a quantidade de segurados
SELECT COUNT(*) AS TOTAL_SEGURADOS FROM SEGURADO;

-- Relatório utilizando sub consulta; [15 pontos]?
-- Retorna todos os segurados que possuem um veículo do modelo Fusca
SELECT * FROM SEGURADO WHERE ID_SEGURADO IN (SELECT SEGURADO_ID_SEGURADO FROM VEICULO WHERE MODELO = 'Fusca');

-- Relatório utilizando junção de tabelas; [15 pontos]?
-- Retorna todos os segurados e seus veículos
SELECT * FROM SEGURADO INNER JOIN VEICULO ON SEGURADO.ID_SEGURADO = VEICULO.SEGURADO_ID_SEGURADO;