DROP SEQUENCE TDSS_TB_CASO_SEQ;

DROP TABLE TDSS_TB_CASO CASCADE CONSTRAINTS;

DROP SEQUENCE TDSS_TB_USER_SEQ;

DROP TABLE TDSS_TB_USER CASCADE CONSTRAINTS;

-- Create a sequence
CREATE SEQUENCE TDSS_TB_CASO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE TDSS_TB_USER_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

CREATE TABLE TDSS_TB_USER (
	CD_USER NUMBER (10) DEFAULT TDSS_TB_USER_SEQ.NEXTVAL NOT NULL,
	NM_USER VARCHAR2 (100) NOT NULL,
	DS_EMAIL VARCHAR2 (100) NOT NULL,
	CONSTRAINT TDSS_TB_USER_PK PRIMARY KEY (CD_USER)
);

-- Create the table with an auto-increment primary key
CREATE TABLE TDSS_TB_CASO (
	CD_CASO NUMBER (10) DEFAULT TDSS_TB_CASO_SEQ.NEXTVAL NOT NULL,
	DS_MARCA VARCHAR2 (100) NOT NULL,
	DS_MODELO VARCHAR2 (100) NOT NULL,
	DS_IMAGEM VARCHAR2 (200) NOT NULL,
	DS_ENDERECO VARCHAR2 (100) NOT NULL,
	DT_CRIACAO DATE NOT NULL,
	DS_STATUS VARCHAR2 (100) NOT NULL,
	CD_USER NUMBER (10) NOT NULL,
	CONSTRAINT TDSS_TB_CASOS_PK PRIMARY KEY (CD_CASO)
);

INSERT INTO TDSS_TB_USER (NM_USER, DS_EMAIL) VALUES ('Augusto Barcelos Barros', 'augustobb@live.com');
INSERT INTO TDSS_TB_USER (NM_USER, DS_EMAIL) VALUES ('Gabriel Gribl', 'gabrielgribl.118@gmail.com');

INSERT INTO TDSS_TB_CASO (DS_MARCA, DS_MODELO, DS_IMAGEM, DS_ENDERECO, DT_CRIACAO, DS_STATUS, CD_USER) VALUES ('Tesla', 'Model 3', 'https://fotos-jornaldocarro-estadao.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2023/09/01213746/1-Tesla-Model-32.jpg', 'Rua Pitangui 102', TO_DATE('2020-04-01', 'YYYY-MM-DD'), 'PENDENTE', 1);

INSERT INTO TDSS_TB_CASO (DS_MARCA, DS_MODELO, DS_IMAGEM, DS_ENDERECO, DT_CRIACAO, DS_STATUS, CD_USER) VALUES ('Audi', 'GT', 'https://cdn.motor1.com/images/mgl/KNqRb/s1/4x3/audi-e-tron-gt-quattro.webp', 'Rua Genofre, 97', TO_DATE('2022-12-26', 'YYYY-MM-DD'), 'PENDENTE', 2);
